version: "3.8"

services:
  #nginx:~

  #mariadb:~

  #app:~

  mailhog:
    image: mailhog/mailhog:latest
    container_name: laravel8auth-mailhog
    restart: unless-stopped
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web api
    networks:
      - laravel8auth